// Command stdlibgen regenerates internal/transpiler/stdlib.go from the current
// Go toolchain's `go list std`, mapping each package qualifier (last path
// segment) to the full import path(s) carrying it. Run from the repo root:
//
//	go run ./internal/transpiler/internal/stdlibgen > internal/transpiler/stdlib.go && gofmt -w internal/transpiler/stdlib.go
package main

import (
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strings"
)

func main() {
	out, err := exec.Command("go", "list", "std").Output()
	if err != nil {
		fmt.Fprintln(os.Stderr, "go list std:", err)
		os.Exit(1)
	}

	byQual := map[string][]string{}
	for _, path := range strings.Fields(string(out)) {
		segs := strings.Split(path, "/")
		// Skip internal-only and vendored packages: never bare-importable.
		skip := false
		for _, s := range segs {
			if s == "internal" || s == "vendor" {
				skip = true
				break
			}
		}
		if skip {
			continue
		}
		qual := segs[len(segs)-1]
		byQual[qual] = append(byQual[qual], path)
	}

	quals := make([]string, 0, len(byQual))
	for q := range byQual {
		quals = append(quals, q)
	}
	sort.Strings(quals)

	var b strings.Builder
	b.WriteString("// Code generated by `go run ./internal/transpiler/internal/stdlibgen`; DO NOT EDIT.\n")
	b.WriteString("// Regenerate after a Go toolchain upgrade to pick up new stdlib packages.\n\n")
	b.WriteString("package transpiler\n\n")
	b.WriteString("// stdlibByQualifier maps a package qualifier (the last segment of a stdlib\n")
	b.WriteString("// import path) to the full import path(s) carrying that qualifier. A qualifier\n")
	b.WriteString("// with exactly one path auto-imports that path; one with several is ambiguous\n")
	b.WriteString("// and yields a \"did you mean\" diagnostic. Single-segment packages (fmt, os, …)\n")
	b.WriteString("// map to themselves.\n")
	b.WriteString("var stdlibByQualifier = map[string][]string{\n")
	for _, q := range quals {
		paths := byQual[q]
		sort.Strings(paths)
		quoted := make([]string, len(paths))
		for i, p := range paths {
			quoted[i] = fmt.Sprintf("%q", p)
		}
		fmt.Fprintf(&b, "\t%q: {%s},\n", q, strings.Join(quoted, ", "))
	}
	b.WriteString("}\n")

	fmt.Print(b.String())
}
